

- name: Windows Update
  win_updates:
    state: installed
  when: windows_update == True
  register: winupdate

- name: Reboot windows to finish updates
  win_reboot:
    reboot_timeout: 900
  when:
    - windows_update == True
    - winupdate.changed

- name: Clean Windows Update packages
  win_command: Dism.exe /online /Cleanup-Image /StartComponentCleanup
  when: windows_update == True

- name: Clean Windows Update service packs
  win_command: Dism.exe /online /Cleanup-Image /SPSuperseded
  when: windows_update == True

- name: Install windows features
  win_feature:
    name: "{{item}}"
  with_items:
    - NFS-Client
    - RSAT-NFS-Admin
    - NET-Framework-Core
    - Desktop-Experience
  register: windows_features

- name: Reboot windows to finish installing features
  win_reboot:
    reboot_timeout: 900
  when: windows_features.changed

- name: Install chocolatey packages
  win_chocolatey:
    name: "{{item}}"
  with_items:
    - autologon
    - psexec
    - vcredist2005
    - vcredist2010
    - directx
    - pscx

- win_stat:
    path: 'C:\Program Files (x86)\SPICE Guest Tools'
  register: chk_spiceinstall

- name: Download redhat driver certificates
  win_copy: src="win-drivers-certs/{{item}}" dest=C:\
  with_items: &cert-list
    - redhat1.cer
    - redhat2.cer
    - redhat3.cer
  when: chk_spiceinstall.stat.exists == False

- name: Trust redhat driver certificates
  win_command: certutil -addstore "TrustedPublisher" C:\{{item}}
  with_items: *cert-list
  when: chk_spiceinstall.stat.exists == False

- name: Remove installed certificates
  win_file: path=C:\{{item}} state=absent
  with_items: *cert-list
  when: chk_spiceinstall.stat.exists == False


- name: Spice guest tools
  win_package:
    path: "https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe"
    arguments: "/S"
    creates_service: vdservice
  when: chk_spiceinstall.stat.exists == False


- name: Disable startup repair
  win_command: "{{item}}"
  with_items:
    - "bcdedit /set {default} recoveryenabled No"
    - "bcdedit /set {default} bootstatuspolicy ignoreallfailures"


- name: Setup Autologon
  win_command: autologon Administrator WORKGROUP {{ansible_password}}


- name: Wallpaper color
  win_regedit:
    path: 'HKCU:\Control Panel\Colors'
    name: Background
    type: string
    data: "86 63 127"
  when: production == True

- name: Wallpaper solid color
  win_regedit:
    path: 'HKCU:\Control Panel\Desktop'
    name: Wallpaper
    type: string
    data: ""
  when: production == True
