---

- name: Base windows config
  ansible.builtin.import_tasks: base.yml

- name: NFS client setup
  ansible.builtin.import_tasks: nfs-mount.yml

- name: NWN2Server install
  ansible.builtin.import_tasks: nwn2server.yml

- name: NWN2Server autostart config
  ansible.builtin.import_tasks: startup.yml
