

- name: Set NFS anon user / gid
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\ClientForNFS\CurrentVersion\Default'
    name: "{{item}}"
    type: dword
    data: 1000
  with_items:
    - AnonymousUid
    - AnonymousGid

# - name: Disable NFS DeleteSymLinks
#   win_regedit:
#     path: 'HKLM:\SOFTWARE\Microsoft\ClientForNFS\CurrentVersion\Default'
#     name: DeleteSymLinks
#     type: dword
#     data: 0

# This allows symlinks inside the NFS mount to be followed
- name: Allow Remote to Remote symlinks
  win_shell: fsutil behavior set SymlinkEvaluation R2R:1

- name: Check if network mappings are mounted
  win_shell: 'Test-Path Z:\'
  register: chk
  failed_when: chk.stdout_lines[0] != "True"
  ignore_errors: yes
  changed_when: False

- name: Mount network drive
  win_shell: 'psexec -i -s net use Z: \\10.0.2.2{{nwn2_path_root}} /persistent:yes'
  when: chk.failed == True