

- name: Check if NWN2Server is installed
  win_shell: 'Test-Path C:\nwn2server\nwn2server.exe'
  register: nwn2server_install
  failed_when: nwn2server_install.stdout_lines[0] != "True"
  ignore_errors: yes
  changed_when: False

- name: Download NWN2Server from URL
  win_get_url:
    url: "{{nwn2server_gamefiles_downloadurl}}"
    dest: '%TEMP%\{{nwn2server_gamefiles_downloadurl | urlsplit("path") | basename}}'
    url_username: "{{nwn2server_gamefiles_downloadurl | urlsplit('username')}}"
    url_password: "{{nwn2server_gamefiles_downloadurl | urlsplit('password')}}"
  when:
    - nwn2server_install is failed
    - nwn2server_gamefiles_downloadurl != ""

  retries: 3
  register: res
  until: res | success

- name: Extracted downloaded NWN2Server
  win_unzip:
    src: '%TEMP%\{{nwn2server_gamefiles_downloadurl | urlsplit("path") | basename}}'
    dest: 'C:\nwn2server'
  when:
    - nwn2server_install is failed
    - nwn2server_gamefiles_downloadurl != ""

- name: Install NWN2Server using local files
  win_copy:
    src: "{{playbook_dir}}/staging/nwn2server"
    dest: 'C:\'
  when:
    - nwn2server_install is failed
    - nwn2server_gamefiles_downloadurl == ""

- name: Install NWN2Server additional DLL files
  win_copy:
    src: "{{item}}"
    dest: 'C:\nwn2server\{{item | basename}}'
  with_fileglob:
    - "{{nwn2_additional_dll_path}}/*.dll"


- name: Allow nwn2server port on win firewall
  win_firewall_rule:
    name: NWN2Server
    localport: "{{nwn2server_port}}"
    action: allow
    direction: in
    protocol: udp
    state: present
    enabled: yes



- name: NWN2 log directory setup
  win_file:
    path: "{{item}}"
    state: directory
  with_items:
    - 'C:\nwn2logs'
    - 'C:\nwn2logs\NWN2'

- name: Create nwn2 logs symlink
  win_command: cmd /c mklink /d C:\nwn2logs\NWN2\LOGS.0 Z:\logs
  args:
    creates: 'C:\nwn2logs\NWN2\LOGS.0'
