


- name: Install NWN2Server
  win_copy:
    src: "{{playbook_dir}}/staging/nwn2server"
    dest: 'C:\'
  register: install_nwn2server

- name: Install NWN2Server additional DLL files
  win_copy:
    src: "{{item}}"
    dest: 'C:\nwn2server\{{item | basename}}'
  with_fileglob:
    - "{{nwn2_additional_dll_path}}/*.dll"


- name: Allow nwn2server port on win firewall
  win_firewall_rule:
    name: NWN2Server
    localport: "{{nwn2_server_port}}"
    action: allow
    direction: in
    protocol: udp
    state: present
    enabled: yes



- name: NWN2 log directory setup
  win_file:
    path: "{{item}}"
    state: directory
  with_items:
    - 'C:\nwn2logs'

- name: Create nwn2 logs symlink
  win_command: cmd /c mklink /d C:\nwn2logs\LOGS.0 Z:\logs
  args:
    creates: 'C:\nwn2logs\LOGS.0'
