
- name: Packages install
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
  tags: [base]



# Unprivileged user
- name: Unprivileged group setup
  group:
    name: "{{unprivileged_user}}"
    gid: "{{unprivileged_uid}}"
  tags: [base]

- name: Unprivileged user setup
  user:
    name: "{{unprivileged_user}}"
    uid: "{{unprivileged_uid}}"
    group: "{{unprivileged_user}}"
  tags: [base]

- authorized_key:
    user: "{{unprivileged_user}}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: [base]



# UFW
- name: UFW Setup
  include_tasks: ufw.yml
  when: use_ufw
  tags: [base]

# nwn-lib-d
- name: NWN2 tools
  include_tasks: nwn-tools.yml
  when: install_nwnlibd_tools
