
- name: Enable universe & multiverse package repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{item}} universe multiverse
    state: present
  with_items:
    - bionic
    - bionic-security
    - bionic-updates

- name: Packages install
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
  tags: [base]



# Unprivileged user
- name: Unprivileged group setup
  group:
    name: "{{unprivileged_user}}"
    gid: "{{unprivileged_gid}}"
  tags: [base]

- name: Unprivileged user setup
  user:
    name: "{{unprivileged_user}}"
    uid: "{{unprivileged_uid}}"
    group: "{{unprivileged_group}}"
  tags: [base]

- authorized_key:
    user: "{{unprivileged_user}}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: [base]



# UFW
- name: UFW Setup
  include_tasks: ufw.yml
  tags: [base]

# qemu network
- name: Qemu network setup
  include_tasks: tap0-network.yml
  tags: [base]

# nwn-lib-d
- name: NWN2 tools
  include_tasks: nwn-tools.yml
  when: install_nwnlibd_tools
