

- name: Qemu network packages install
  apt:
    name: "{{item}}"
  with_items:
    - isc-dhcp-server

- name: Check if TAP device exists
  shell: ip link show tap0
  register: tap_device_check
  ignore_errors: yes
  changed_when: False

- name: Create TAP device
  shell: |
    ip tuntap add name tap0 mode tap
    ip link set tap0 up
  when: tap_device_check.rc != 0



- name:
  interfaces_file:
    dest: /etc/network/interfaces.d/tap0.cfg
    iface: tap0
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - {option: address, value: 10.0.2.1}
    - {option: netmask, value: 255.255.255.0}

- name: make interface up
  net_interface:
    name: tap0
    enabled: True

- name: Configure UFW to NAT virtual machine's network
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: '^\*filter'
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Qemu NAT setup"
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      COMMIT

- name: Configure DHCP server to listen to tap0
  blockinfile:
    path: /etc/default/isc-dhcp-server
    block: |
      INTERFACESv4="tap0"

- name: Configure tap0 DHCP server
  blockinfile:
    path: /etc/dhcp/dhcpd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK: tap0 DHCP server"
    block: |
      option domain-name "";
      option domain-name-servers 9.9.9.9, 1.1.1.1;
      option subnet-mask 255.255.255.0;
      option routers 10.0.2.1;

      subnet 10.0.2.0 netmask 255.255.255.0 {
        range 10.0.2.20 10.0.2.100;
      }

- name: Enable & start DHCP server
  systemd:
    name: "isc-dhcp-server.service"
    state: started
    enabled: yes