---

- name: Install UFW
  ansible.builtin.apt:
    name: ufw

- name: "UFW: rate-limit SSH"
  community.general.ufw:
    rule: limit
    name: OpenSSH

- name: "UFW: enable"
  community.general.ufw:
    state: enabled
