


- name: Generate backup SSH key
  become: true
  become_user: "{{unprivileged_user}}"
  command: ssh-keygen -P "" -C backup@{{ansible_hostname}} -t ed25519 -f {{backup_keyfile}}
  args:
    creates: "{{backup_keyfile}}"

- name: Copy backup script
  template:
    src: backup.j2
    dest: "{{nwn2_path_root}}/bin/backup"
    mode: 0755

- name: Copy backup-restore script
  template:
    src: backup-restore.j2
    dest: "{{nwn2_path_root}}/bin/backup-restore"
    mode: 0755


- name: Copy backup service & timer
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{(item| basename | splitext)[0]}}"
    mode: 0644
  with_items:
    - backup@.service.j2
    - backup@.timer.j2

- name: Enable backup timer
  systemd:
    name: backup@{{nwn2_path_root | basename}}.timer
    enabled: yes

- name: Add remote server to known hosts
  become: true
  become_user: "{{item}}"
  known_hosts:
    name: "{{backup_server}}"
    key: "{{backup_server_key}}"
  with_items:
    - "{{unprivileged_user}}"
    - root