---

#
# -------------------- Disk image
#
- name: Check if qemu disk is present
  ansible.builtin.stat:
    path: "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}"
    get_checksum: false
  register: _nwn2server_stat_qemudisk

- name: Extract Qemu compressed disk from target disk
  ansible.builtin.shell: xz -d -T0 --stdout "{{ qemu_disk_download_url }}" > "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}"
  args:
    creates: "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}"
  when:
    - _nwn2server_stat_qemudisk.stat.exists is false
    - qemu_disk_download_url | urlsplit('scheme') == ''

- name: Upload local qemu compressed disk to target
  ansible.builtin.copy:
    src: "{{ qemu_disk_download_url | urlsplit('path') }}"
    dest: "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}{{ (qemu_disk_download_url | urlsplit('path') | splitext)[1] }}"
    mode: "0600"
  when:
    - _nwn2server_stat_qemudisk.stat.exists is false
    - qemu_disk_download_url | urlsplit('scheme') == 'file'

- name: Download Qemu compressed disk from URL
  ansible.builtin.get_url:
    url: "{{ qemu_disk_download_url }}"
    dest: "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}{{ (qemu_disk_download_url | urlsplit('path') | splitext)[1] }}"
    mode: "0600"
  when:
    - _nwn2server_stat_qemudisk.stat.exists is false
    - qemu_disk_download_url | urlsplit('scheme') != ''
    - qemu_disk_download_url | urlsplit('scheme') != 'file'

- name: Extract Qemu disk
  ansible.builtin.command:
    xz -d -T0 "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}{{ (qemu_disk_download_url | urlsplit('path') | splitext)[1] }}"
  args:
    creates: "{{ nwn2_path_root }}/nwn2server-vmdisk.{{ qemu_disk_format }}"
  when:
    - _nwn2server_stat_qemudisk.stat.exists is false
    - qemu_disk_download_url | urlsplit('scheme') != ''

#
# -------------------- Libvirt config
#
- name: Install libvirt hook for redirecting ports
  ansible.builtin.copy:
    dest: /etc/libvirt/hooks-custom/before-
    mode: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail

      # Setup nwn2server port forwarding
      if ! iptables -t nat -C PREROUTING -p udp --dport {{ nwn2server_public_port }} -j DNAT --to {{ nwn2server_private_ip }}:5121; then
        iptables -t nat -A PREROUTING -p udp --dport {{ nwn2server_public_port }} -j DNAT --to {{ nwn2server_private_ip }}:5121
      fi
      if ! iptables -C FORWARD -d {{ nwn2server_private_ip }} -p udp --dport 5121 -j ACCEPT; then
       	iptables -A FORWARD -d {{ nwn2server_private_ip }} -p udp --dport 5121 -j ACCEPT
      fi

- name: Install VM XML
  community.libvirt.virt:
    name: nwn2server-{{ nwn2_path_root | basename }}
    command: define
    autostart: true
    xml: "{{ lookup('template', 'libvirt.xml.j2') }}"


#
# -------------------- Misc
#
- name: Copy controller script
  ansible.builtin.template:
    src: nwn2server-controller.j2
    dest: "{{ nwn2_path_root }}/bin/nwn2server-controller"
    mode: "0755"

- name: "UFW: Enable NWN2Server port"
  community.general.ufw:
    rule: allow
    port: "{{ nwn2server_public_port | string }}"
    proto: udp

- name: Configure static IP for the VM
  ansible.builtin.blockinfile:
    path: /etc/dnsmasq.d/qemu-tap0
    marker: "# {mark} ANSIBLE MANAGED BLOCK: static IP for {{ nwn2_path_root }}"
    block: |
      dhcp-host=52:55:00:d1:55:{{ "%02x" | format(nwn2server_private_ip.split(".")[3] | int) }},{{ nwn2server_private_ip }}
  notify: Restart dnsmasq
