



- name: NWN2Server folder creation
  file:
    path: "{{item}}"
    owner: "{{unprivileged_user}}"
    group: "{{unprivileged_user}}"
    state: directory
  with_items:
    - "{{nwn2_path_root}}"
    - "{{nwn2_path_root}}/bin"
    - "{{nwn2_path_root}}/logs"
    - "{{nwn2_path_root}}/nwnx4"
    - "{{nwn2_path_root}}/home"
    - "{{nwn2_path_root}}/home/servervault"
    - "{{nwn2_path_root}}/home/override"

# Shares
- import_tasks: servervault-mount.yml
- import_tasks: nfs-server.yml

# MySQL server
- import_tasks: sql.yml

# NWN2 Home (Documents/Neverwinter Nights 2)
- import_tasks: nwn2home.yml

# NWNX4
- import_tasks: nwnx4.yml

# Virtualization
- import_tasks: qemu.yml

- import_tasks: tooling.yml
