

- name: Install NFS package
  apt:
    name: nfs-server
    state: latest


- name: remove legacy exports
  blockinfile:
    path: /etc/exports
    state: absent
  register: nfsexport_rmlegacy

# TODO: Breaks file rights as anybody (on localhost) can mount and
#       read/writes files exported as the unprivileged user
- name: Set exports for NWN2 home
  blockinfile:
    path: /etc/exports
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: mounts for {{nwn2_path_root}}"
    block: |
      "{{nwn2_path_root}}"               {{nwn2server_private_ip}}(fsid=0,insecure,rw,all_squash,anonuid={{unprivileged_uid}},anongid={{unprivileged_gid}},no_subtree_check,crossmnt,async)
      {% if nwn2server_override_tmpfs %}
      "{{nwn2_path_root}}/home/override" {{nwn2server_private_ip}}(fsid=1,insecure,rw,all_squash,anonuid={{unprivileged_uid}},anongid={{unprivileged_gid}},no_subtree_check)
      {% endif %}
  register: nfsexport

- name: Update exports
  command: exportfs -ra
  when: nfsexport.changed or nfsexport_rmlegacy.changed

- name: Start & enable NFS service
  systemd:
    name: nfs-server.service
    state: started
    enabled: yes