---

- name: Install NFS package
  ansible.builtin.apt:
    name: nfs-server


- name: Remove legacy exports
  ansible.builtin.blockinfile:
    path: /etc/exports
    state: absent
  register: _nwn2server_nfsexport_rmlegacy

# TODO: Breaks file rights as anybody (on localhost) can mount and
#       read/writes files exported as the unprivileged user
- name: Set exports for NWN2 home
  ansible.builtin.blockinfile:
    path: /etc/exports
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: mounts for {{ nwn2_path_root }}"
    # yamllint disable rule:line-length
    block: |
      "{{ nwn2_path_root }}"               {{ nwn2server_private_ip }}(fsid=0,insecure,rw,all_squash,anonuid={{ unprivileged_uid }},anongid={{ unprivileged_gid }},no_subtree_check,crossmnt,async)
      {% if nwn2server_override_tmpfs %}
      "{{ nwn2_path_root }}/home/override" {{ nwn2server_private_ip }}(fsid=1,insecure,rw,all_squash,anonuid={{ unprivileged_uid }},anongid={{ unprivileged_gid }},no_subtree_check)
      {% endif %}
    # yamllint enable rule:line-length
  register: _nwn2server_nfsexport

- name: Update exports
  ansible.builtin.command: exportfs -ra
  when: _nwn2server_nfsexport.changed or _nwn2server_nfsexport_rmlegacy.changed
  changed_when: false

- name: Start & enable NFS service
  ansible.builtin.systemd_service:
    name: nfs-server.service
    state: started
    enabled: true
