
- name: Create NWN2 folders
  become: true
  become_user: "{{unprivileged_user}}"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{nwn2_path_root}}/home/campaigns"
    - "{{nwn2_path_root}}/home/database"
    - "{{nwn2_path_root}}/home/hak"
    - "{{nwn2_path_root}}/home/modules"
    - "{{nwn2_path_root}}/home/override"
    - "{{nwn2_path_root}}/home/override.disk"
    - "{{nwn2_path_root}}/home/pwc"
    - "{{nwn2_path_root}}/home/saves"
    - "{{nwn2_path_root}}/home/servervault"
    - "{{nwn2_path_root}}/home/tlk"

- name: Create NWN2 override tmpfs backup folder
  become: true
  become_user: "{{unprivileged_user}}"
  file:
    path: "{{nwn2_path_root}}/home/override.disk"
    state: directory
  when: nwn2server_override_tmpfs

- name: Setup tmpfs for override folder
  mount:
    path: "{{nwn2_path_root}}/home/override"
    src: tmpfs
    fstype: tmpfs
    opts: nodev,nosuid,size={{nwn2server_override_maxsize}}
    state: mounted
  register: override_tmpfs_setup
  when: nwn2server_override_tmpfs

- name: Copy tmpfs restore service file
  template:
    src: nwn2server-tmpfs-restore@.service.j2
    dest: /etc/systemd/system/nwn2server-tmpfs-restore@.service
    mode: 0644
  when: nwn2server_override_tmpfs

- name: Enable tmpfs restore service
  systemd:
    name: nwn2server-tmpfs-restore@{{nwn2_path_root | basename}}.service
    state: started
    enabled: yes
  when: nwn2server_override_tmpfs and override_tmpfs_setup.changed

- name: Write nwn2player.ini
  become: true
  become_user: "{{unprivileged_user}}"
  template:
    src: nwn2player.ini.j2
    dest: "{{nwn2_path_root}}/home/nwn2player.ini"
    mode: 0644
