
# Note: At the moment, the nwnx4 files distributed on nwnx.org are broken
- name: Install nwnx files
  copy:
    src: "{{role_path}}/files/nwnx4/{{item.path}}"
    dest: "{{nwn2_path_root}}/nwnx4/"
    mode: "{{item.mode}}"
  with_items:
    - {path: NWNX4_Controller.exe, mode: 755}
    - {path: NWNX4_GUI.exe, mode: 755}
    - {path: NWNX4_Hook.dll, mode: 755}
    - {path: xp_mysql.dll, mode: 755}
    - {path: xp_time.dll, mode: 755}
    - {path: licence.txt, mode: 644}

- name: Install nwnx4 config files
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_items:
    - nwnx.ini.j2
    - xp_mysql.ini.j2

- name: Install additional nwnx4 plugins (ini and dll files only)
  copy:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4"
    mode: "{{((item | splitext)[1] == '.dll') | ternary(0755, 0644)}}"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.ini"
    - "{{nwnx4_additional_plugin_path}}/*.dll"

- name: Install additional nwnx4 config templates
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.j2"

