
- name: Download & unzip nwnx archive
  unarchive:
    remote_src: yes
    src: 'https://www.nwnx.org/fileadmin/download/nwnx4_109_preview1.zip'
    dest: /tmp
    creates: /tmp/nwnx4

- name: Create nwnx4 folder
  file:
    path: "{{nwn2_path_root}}/nwnx4"
    state: directory
    owner: "{{unprivileged_user}}"

- name: Check if nwnx4 files are present
  stat:
    path: /tmp/nwnx4
  register: nwnx4_extracted

- name: Install nwnx files
  copy:
    remote_src: true
    src: "{{item.path}}"
    dest: "{{nwn2_path_root}}/nwnx4/"
    mode: "{{item.mode}}"
  with_items:
    - {path: /tmp/nwnx4/NWNX4_Controller.exe, mode: 755}
    - {path: /tmp/nwnx4/NWNX4_GUI.exe, mode: 755}
    - {path: /tmp/nwnx4/NWNX4_Hook.dll, mode: 755}
    - {path: /tmp/nwnx4/xp_mysql.dll, mode: 755}
    - {path: /tmp/nwnx4/xp_time.dll, mode: 755}
    - {path: /tmp/nwnx4/licence.txt, mode: 644}
  when: nwnx4_extracted.stat.exists

- name: Install nwnx4 config files
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_items:
    - nwnx.ini.j2
    - xp_mysql.ini.j2

- name: Install additional nwnx4 plugins (ini and dll files only)
  copy:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4"
    mode: "{{((item | splitext)[1] == '.dll') | ternary(0755, 0644)}}"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.ini"
    - "{{nwnx4_additional_plugin_path}}/*.dll"

- name: Install additional nwnx4 config templates
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.j2"

