
- name: Create dir for storing nwnx4 zip file
  file:
    path: "/var/ansible-nwn2server/"
    state: directory

- name: Download latest nwnx4 release
  get_url:
    url: "{{nwnx4_upstream}}"
    dest: /var/ansible-nwn2server/nwnx4.zip
  register: nfsexport_rmlegacy

- name: extract NWNX4
  unarchive:
    src: "{{nwnx4_upstream}}"
    dest: "{{nwn2_path_root}}/"
    remote_src: yes

- name: Install nwnx4 config files
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_items:
    - nwnx.ini.j2
    - xp_mysql.ini.j2

- name: Install additional nwnx4 plugin dll files
  copy:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/plugins/"
    mode: "0755"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.dll"
    - "{{nwnx4_additional_plugin_path}}/*.pdb"

- name: Install additional nwnx4 ini files
  copy:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4"
    mode: "0644"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.ini"

- name: Install additional nwnx4 config templates
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: "0644"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.j2"

