---

- name: Create dir for storing nwnx4 zip file
  ansible.builtin.file:
    path: "/var/ansible-nwn2server/"
    state: directory
    mode: "0755"

- name: Create nwnx4 user config dir
  ansible.builtin.file:
    path: "{{ nwn2_path_root }}/nwnx4-user/"
    state: directory
    mode: "0755"

- name: Download latest nwnx4 release
  ansible.builtin.get_url:
    url: "{{ nwnx4_upstream }}"
    dest: /var/ansible-nwn2server/nwnx4.zip
    mode: "0644"

- name: Extract NWNX4
  ansible.builtin.unarchive:
    src: "/var/ansible-nwn2server/nwnx4.zip"
    dest: "{{ nwn2_path_root }}"
    remote_src: true

- name: Install nwnx4 config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ nwn2_path_root }}/nwnx4-user/{{ (item | basename | splitext)[0] }}"
    mode: "0644"
  with_items:
    - nwnx.ini.j2
    - xp_mysql.ini.j2

- name: Install additional nwnx4 plugin dll files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nwn2_path_root }}/nwnx4-user/plugins/"
    mode: "0755"
  with_fileglob:
    - "{{ nwnx4_additional_plugin_path }}/*.dll"
    - "{{ nwnx4_additional_plugin_path }}/*.pdb"

- name: Install additional nwnx4 ini files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nwn2_path_root }}/nwnx4-user"
    mode: "0644"
  with_fileglob:
    - "{{ nwnx4_additional_plugin_path }}/*.ini"

- name: Install additional nwnx4 config ansible.builtin.templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ nwn2_path_root }}/nwnx4-user/{{ (item | basename | splitext)[0] }}"
    mode: "0644"
  with_fileglob:
    - "{{ nwnx4_additional_plugin_path }}/*.j2"
