
- name: Download & unzip nwnx archive
  unarchive:
    remote_src: yes
    src: 'http://nwnx.org/typo3conf/ext/nf_downloads/pi1/passdownload.php?downloaddata=13'
    dest: /tmp
    creates: /tmp/nwnx4

- name: Create nwnx4 folder
  file:
    path: "{{nwn2_path_root}}/nwnx4"
    state: directory
    owner: "{{unprivileged_user}}"

- name: Install nwnx files
  copy:
    remote_src: true
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/"
    mode: 755
  with_items:
    - /tmp/nwnx4/NWNX4_Controller.exe
    - /tmp/nwnx4/NWNX4_GUI.exe
    - /tmp/nwnx4/NWNX4_Hook.dll
    - /tmp/nwnx4/xp_mysql.dll
    - /tmp/nwnx4/xp_time.dll

- name: Install nwnx4 config files
  template:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4/{{(item | basename | splitext)[0]}}"
    mode: 0644
  with_items:
    - nwnx.ini.j2
    - xp_mysql.ini.j2

- name: Install additional nwnx4 plugins (ini and dll files only)
  copy:
    src: "{{item}}"
    dest: "{{nwn2_path_root}}/nwnx4"
    mode: "{{((item | splitext)[1] == '.dll') | ternary(0755, 0644)}}"
  with_fileglob:
    - "{{nwnx4_additional_plugin_path}}/*.ini"
    - "{{nwnx4_additional_plugin_path}}/*.dll"

