

- name: Qemu Packages install
  apt:
    name: "{{item}}"
  with_items:
    - qemu
    - qemu-kvm


- name: Download/extract qemu disk
  unarchive:
    remote_src: "{{qemu_disk_download_url | urlsplit('scheme') != ''}}"
    src: "{{qemu_disk_download_url}}"
    dest: "{{nwn2_path_root}}/nwn2server-vmdisk.{{qemu_disk_format}}"
    creates: "{{nwn2_path_root}}/nwn2server-vmdisk.{{qemu_disk_format}}"


- name: Copy nwn2server launch script
  template:
    src: qemu-launch.j2
    dest: "{{nwn2_path_root}}/bin/launch"
    mode: 0755

- name: Copy nwn2server service file
  template:
    src: nwn2server@.service.j2
    dest: /etc/systemd/system/nwn2server@.service
    mode: 0644

- name: Enable nwn2server
  systemd:
    name: "nwn2server@{{nwn2_path_root | basename}}.service"
    # state: started
    enabled: yes

- name: "UFW: Enable NWN2Server port"
  ufw:
    rule: allow
    port: "{{nwn2_server_port}}"
    proto: udp