---

- name: Install NTFS package
  ansible.builtin.apt:
    name: ntfs-3g

- name: Allocate Servervault NTFS file
  ansible.builtin.command: fallocate -l {{ servervault_ntfspart_size }} "{{ servervault_ntfspart }}"
  args:
    creates: "{{ servervault_ntfspart }}"
  register: nwn2server_ntfs_fallocate

- name: Write filesystem
  ansible.builtin.command: /sbin/mkntfs -F "{{ servervault_ntfspart }}"
  changed_when: true
  when: nwn2server_ntfs_fallocate.changed  # noqa: no-handler

- name: Mount filesystem
  ansible.posix.mount:
    path: "{{ nwn2_path_root }}/home/servervault"
    src: "{{ servervault_ntfspart }}"
    fstype: ntfs
    opts: "rw,exec,uid={{ unprivileged_uid }},gid={{ unprivileged_gid }},dmask=022,fmask=133"
    state: mounted
