- name: Install MySQL package
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
      - python-pymysql
    state: latest

- name: Set MySQL to listen on all interfaces
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^\s*bind-address\s*=\s*.+$'
    insertafter: '\[mysqld\]'
    line: 'bind-address = 0.0.0.0'
  register: conf_changed

- name: Start & enable MySQL service
  systemd:
    name: mysql.service
    state: "{{'restarted' if conf_changed.changed else 'started'}}"
    enabled: yes

- name: Add nwnx database
  mysql_db:
    name: nwnx
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add MySQL User
  mysql_user:
    name: "{{mysql_user}}"
    host: "{{qemu_tap_network.split('.')[0:3] | join('.')}}.%"
    password: "{{mysql_password}}"
    priv: "{{mysql_database}}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock


