- name: Install MySQL package
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: latest
  tags: [sql]

- name: Set MySQL to listen on all interfaces
  community.general.ini_file:
    path: /etc/mysql/mariadb.cnf
    section: mysqld
    option: bind-address
    value: '0.0.0.0'
  register: conf_changed

- name: Start & enable MySQL service
  systemd:
    name: mariadb.service
    state: "{{'restarted' if conf_changed.changed else 'started'}}"
    enabled: yes

- name: Add {{mysql_database}} database
  mysql_db:
    name: "{{mysql_database}}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [sql]

- name: Add MySQL User
  mysql_user:
    name: "{{mysql_user}}"
    host: "{{item}}"
    password: "{{mysql_password}}"
    priv: "{{mysql_database}}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{qemu_tap_network.split('.')[0:3] | join('.')}}.%"
    - "localhost"
  tags: [sql]
