---

- name: Install MySQL package
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
  tags: [sql]

- name: Set MySQL to listen on all interfaces
  community.general.ini_file:
    path: /etc/mysql/mariadb.conf.d/99-nwn2server.cnf
    section: mysqld
    option: bind-address
    value: "127.0.0.1,{{ qemu_tap_network_prefix24 }}.0"
    mode: "0644"
  register: _nwn2server_conf_changed
  tags: [sql]

- name: Start & enable MySQL service
  ansible.builtin.systemd_service:
    name: mariadb.service
    state: "{{ 'restarted' if _nwn2server_conf_changed.changed else 'started' }}"
    enabled: true
  tags: [sql]

- name: "Add mysql database {{ mysql_database }}"
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [sql]

- name: Add MySQL User
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    host: "{{ item }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{ qemu_tap_network_prefix24 }}.%"
    - "localhost"
    - "127.0.0.1"
  tags: [sql]
