


- name: Register mariadb apt key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.pgp
  tags: [sql]

- name: Add mariadb ppa
  apt_repository:
    repo: deb [arch=amd64] {{mariadb_mirror}}/{{mariadb_version}}/ubuntu {{ansible_distribution_release}} main
    filename: mariadb
    state: present
  tags: [sql]

- name: Install MySQL package
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: latest
  tags: [sql]

- name: Set MySQL to listen on all interfaces
  community.general.ini_file:
    path: /etc/mysql/mariadb.conf.d/99-nwn2server.cnf
    section: mysqld
    option: bind-address
    value: '0.0.0.0' # Note: the UFW will filter connections
  register: conf_changed
  tags: [sql]

- name: Start & enable MySQL service
  systemd:
    name: mariadb.service
    state: "{{'restarted' if conf_changed.changed else 'started'}}"
    enabled: yes
  tags: [sql]

- name: Add {{mysql_database}} database
  mysql_db:
    name: "{{mysql_database}}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [sql]

- name: Add MySQL User
  mysql_user:
    name: "{{mysql_user}}"
    host: "{{item}}"
    password: "{{mysql_password}}"
    priv: "{{mysql_database}}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{qemu_tap_network.split('.')[0:3] | join('.')}}.%"
    - "localhost"
    - "127.0.0.1"
  tags: [sql]
