- name: Install MySQL package
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
      - python-pymysql
    state: latest

- name: Start & enable MySQL service
  systemd:
    name: mysql.service
    state: started
    enabled: yes

- name: Add nwnx database
  mysql_db:
    name: nwnx
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add MySQL User
  mysql_user:
    name: "{{mysql_user}}"
    host: localhost
    password: "{{mysql_password}}"
    priv: "{{mysql_database}}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
