


- name: LcdaAccountManager packages install
  apt: name={{item}}
  with_items:
    - redis-server
    - libevent-pthreads*

- name: Start & enable redis server
  systemd:
    name: redis.service
    state: started
    enabled: yes

- name: LcdaAccountManager binary install
  copy:
    src: "{{playbook_dir}}/staging/LcdaAccountManager/lcdaaccountmanager"
    dest: /usr/local/bin/lcdaaccountmanager
    mode: 0755


- name: Create LcdaAccountManager config folder
  file:
    path: /srv/accountmanager
    state: directory

- name: LcdaAccountManager public files install
  file:
    src: "{{playbook_dir}}/staging/LcdaAccountManager/public"
    dest: /srv/accountmanager/

- name: LcdaAccountManager config install
  template:
    src: public-api.config.json.j2
    dest: /srv/accountmanager/config.json
    mode: 0644
  env:
    lcdaapi_port: "{{accountmanager_port}}"

- name: LcdaAccountManager dialog.tlk install
  copy:
    src: "{{playbook_dir}}/staging/nwn2server/dialog.TLK"
    dest: /srv/api/dialog.tlk
    mode: 644

- name: Add Caddy LcdaAccountManager reverse proxy config
  blockinfile:
    path: /etc/Caddyfile
    marker: "# {mark} ANSIBLE MANAGED BLOCK: LcdaAccountManager"
    content: |
      {{accountmanager_listen}} {
        proxy / 127.0.0.1:{{accountmanager_port}}
      }
  notify: reload caddy


- name: LcdaAccountManager service file
  template:
    src: lcdaaccountmanager.service.j2
    dest: /etc/systemd/system/lcdaaccountmanager.service
    mode: 0644

- name: Start & enable LcdaAccountManager service
  systemd:
    name: lcdaaccountmanager.service
    state: started
    enabled: yes
