

- name: Create adl directory
  file:
    path: "{{adl_path}}"
    state: directory
    owner: "{{unprivileged_user}}"
    group: "{{unprivileged_user}}"


- name: Add Caddy Autodownloader config
  blockinfile:
    path: /etc/Caddyfile
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Autodownloader"
    content: |
      http://{{adl_listen}}
      https://{{adl_listen}} {
        root {{adl_path}}
        browse
      }
  notify: reload caddy
