
- name: Install ZSH
  apt:
    name: zsh
    state: latest

- name: Clone OhMyZSH
  become: true
  become_user: "{{user}}"
  git:
    repo: https://github.com/CromFr/crom-custom-oh-my-zsh.git
    dest: ~/.oh-my-zsh
    version: HEAD

- name: Install .zshrc
  become: true
  become_user: "{{user}}"
  copy:
    remote_src: True
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc

- name: Set ZSH theme
  become: true
  become_user: "{{user}}"
  replace:
    path: ~/.zshrc
    regexp: '^ZSH_THEME=.*?$'
    replace: 'ZSH_THEME="{{theme}}"'

- name: Set prompt prefix
  become: true
  become_user: "{{user}}"
  replace:
    path: ~/.zshrc
    regexp: '^PROMPT_SPECIAL=.*?$'
    replace: 'PROMPT_SPECIAL="{{prompt_prefix}}"'

- name: Change default shell
  user:
    name: "{{user}}"
    shell: /bin/zsh

