production: False
windows_update: False

# Host unprivileged user info
unprivileged_user: nwn2
unprivileged_uid: 1000

# Host nwn2server path for NFS mounting
nwn2_path_root: /srv/nwn2server

nwn2_server_port: 5121