production: False

# Just checking windows updates can take a lot of time
windows_update: False

# Host unprivileged user info
unprivileged_uid: 1000

# Host nwn2server path for NFS mounting
nwn2_path_root: /srv/nwn2server

# Change this path to set a custom dir to provision nwn2server additional DLL files (that can be versionned)
nwn2_additional_dll_path: "{{playbook_dir}}/staging/nwn2server-dll"

# Define this variable to download the nwn2server game files from another server (compressed zip format)
# If set to "", it will upload the content from staging/nwn2server
nwn2server_gamefiles_downloadurl: ""

qemu_tap_network: "10.0.2.0"