

unprivileged_user: nwn2
unprivileged_uid: 1000

use_ufw: True


# Base path where data will be stored. Must be a direct sub-folder of /srv (see service files)
nwn2_path_root: /srv/nwn2server

# NWN2Server port
nwn2_server_port: 5121

nwnx4_nwn2server_parameters: "-moduledir YourModule"
nwnx4_mysql_loglevel: "1"
# Change this path to set a custom dir to provision nwnx4 additional plugins & configuration (that can be versionned)
nwnx4_additional_plugin_path: "{{playbook_dir}}/staging/nwnx4_plugins"

# HTTP/HTTPS/FTP url to download the compressed windows disk image.
# If it is a local file path, it will send from your system (can be very slow)
# Any compression can be used
qemu_disk_download_url: "https://user:password@yoursite.com/path/to/disk.raw.xz"
# Qemu disk image format (raw, qcow2, ...)
qemu_disk_format: "raw"

# Remote desktop port
qemu_spice_port: 3389

# Port for controlling the vm using telnet (see qemu -monitor arg)
qemu_monitor_port: 3390

mysql_host: 10.0.2.2
mysql_database: "nwnx"
mysql_user: "nwnx"
mysql_password: "password"

# This partition will be mounted and will contain the servervault content.
# NTFS is needed as files are ordered by name (rather than their hash values),
#  and nwn2 doesn't sort characters when listing them in the character selection menu
# This partition will be mounted in "{{nwn2_home}}/servervault"
servervault_ntfspart: "{{nwn2_path_root}}/servervault.ntfs"
servervault_ntfspart_size: 2G
