

unprivileged_user: nwn2
unprivileged_uid: 1000


# Base path where data will be stored. Must be a direct sub-folder of /srv
# (see service files)
nwn2_path_root: /srv/nwn2server
# Private IP to assign to the NWN2 server VM. Must be in the 10.0.2.0/24
# network, and not 10.0.2.1.
# Note: the last number will be used to set the
# virtual machine mac address
nwn2server_private_ip: 10.0.2.10
# The port used to connect to the nwn2server from the outside. Internally the
# nwn2server VM will always listen to 5121, and the host will forward ports to
# the appropriate VM
nwn2server_public_port: 5121

# NWN2Server config
nwn2server_name: "NWN2 server managed with Ansible"
nwn2server_playerpassword: ""
nwn2server_dmpassword: ""

# If true, the NWN2 override folder will be loaded into RAM for improving
# server performance. The module files should be stored in the override folder
# (except the module.ifo file) otherwise the nwn2server instance will copy
# every module file into a temporary folder on disk.
nwn2server_override_tmpfs: true
# Maximum size of the override folder
nwn2server_override_maxsize: 2G

nwnx4_nwn2server_parameters: "-moduledir YourModule"
nwnx4_mysql_loglevel: "1"
# Change this path to set a custom dir to provision nwnx4 additional plugins & configuration (that can be versionned)
nwnx4_additional_plugin_path: "{{playbook_dir}}/staging/nwnx4_plugins"

# HTTP/HTTPS/FTP url to download the compressed windows disk image.
# If it is a local file path, it will send from your system (can be very slow)
# Any compression can be used.
# The download step is skipped if there is a file in "{{nwn2_path_root}}/nwn2server-vmdisk.{{qemu_disk_format}}"
qemu_disk_download_url: "https://user:password@yoursite.com/path/to/disk.raw.xz"
# Qemu disk image format (raw, qcow2, ...)
qemu_disk_format: "raw"

# Qemu processor allocation (-smp arg).
# NWN2Server uses only 1 thread, but more CPU can be allocated to take care of windows tasks.
qemu_smp: "cores=1,threads=1,sockets=1"

# Remote desktop port
qemu_spice_port: 3389

# MySQL host address in the tap0 network. should not be changed.
mysql_host: 10.0.2.1
mysql_database: "nwnx"
mysql_user: "nwnx"
mysql_password: "password"

# This partition will be mounted and will contain the servervault content.
# NTFS is needed in order to have a correctly sorted character list.
# This partition will be mounted in "{{nwn2_home}}/servervault"
servervault_ntfspart: "{{nwn2_path_root}}/servervault.ntfs"
# Size of the partition hosting the servervault
servervault_ntfspart_size: 2G


# Virtual machine windows access configuration
windows_user: Administrator
windows_password: "YourWindowsPassword"
winrm_port: 5985